---

- name: Add apt_repository
  apt_repository:
    repo: 'ppa:kelleyk/emacs'
    state: present
  become: yes

- name: Installing emacs27
  apt:
    name: emacs27
    update_cache: yes
  become: yes
