local1:
  hosts:
    localjov
  vars:
    ansible_connection: local
local2:
  hosts:
    localphil
  vars:
    ansible_connection: local
do:
  hosts:
    do1
dojov:
  hosts:
    do1jov
j2jov:
  hosts:
    j2jov
n1phil:
  hosts:
    n1
    
